@extends('master')

@title('Welcome to Foundation!')

@section('content')
	Welcome to Foundation! This page is being generated by ~/views/home.blade.php from a route defined in ~/webapp.php.
@endsection